[package]
name = "actix_otel_sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

actix-web = "4"
anyhow = "1.0.75"
askama = "0.12.1"
askama_actix = "0.14.0"
chrono = "0.4.31"
dotenvy = "0.15.7"
serde = "1.0.189"
sqlx = { version = "0.7", features = [
    "runtime-tokio",
    "postgres",
    "macros",
    "chrono",
] }
tracing = "0.1.40"
tracing-actix-web = "0.7.8"
tracing-subscriber = "0.3.17"
opentelemetry = "0.20.0"
opentelemetry-otlp = "0.13.0"
tokio = { version = "1", features = ["full"] }
