[package]
name = "actix_otel_sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.7", features = [
    "runtime-tokio",
    "postgres",
    "macros",
    "chrono",
] }
actix-web = "4"
askama = "0.12.1"
askama_actix = "0.14.0"
anyhow = "1.0.75"
dotenvy = "0.15.7"
serde = "1.0.189"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
chrono = "0.4.31"
