services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=${DB_URL}
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./templates
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    # expose:
    #   - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
